### ISSUE TITLE
AHV Nummern in bestehende Events übertragen & auf Personendaten löschen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_youth#59]
Umsetzungsticket zur Diskussion in https://github.com/hitobito/hitobito/issues/2162

### Voraussetzung: 
#58  ist umgesetzt

### Ausgangslage:
Da die AHV Nummer neu in Events gespeichert wird, sollen einmalig alle AHV-Nummern in die aktiven Events übertragen werden. Anschliessend werden die AHV-Nummern in den Personendaten endgültig gelöscht.

### Umsetzung:
- Einmalige Migration aller AHV Nummern von den Personendaten in die aktiven Events.
- Das AHV-Nummer Feld auf den Personendaten und sämtliche Inhalte darin werden gelöscht.
  - Cevi und Jubla haben auch noch ein Feld "AHV-Alt" dieses wird ebenfalls gelöscht.
- Exporte anpassen, damit AHV-Nummer nicht mehr in Exports vorhanden ist.

# Tech-Spec

- nicht benötigte Personendaten löschen
- AHV-Nummer von Teilnehmern auf aktive Events übertragen
- als aktive Events werden alle mit einem (Start- oder End-) Datum ab heute oder in der Zukunft verstanden. Events, die komplett in der Vergangenheit liegen, werden nicht mit den AHV-Nummern angereichert.

# ToDo

- [x] Migration erstellen
    - AHV-Nummer von Personen auf Teilnahme verschieben
    - Spalte AHV-Nummer löschen
    - Spalte AHV-Alt löschen
- [x] Eingabefelder für AHV-Nummer verstecken
- [x] Validierung für AHV-Nummer löschen
- [x] AHV-Nummer aus Exporten entfernen
- [x] weitere Referenzen auf AHV-Nummer prüfen und möglichst entfernen
- [x] Specs anpassen und schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [ ] Sämtliche Youth Kunden vorgängig informieren dass die Migration mit dem nächsten Release ausgeführt wird.

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Bitte um ein Update zum Release.


Wir sehen die Einmalige Migration aller AHV Nummern von den Personendaten in die aktiven Events nicht.

**Comment by richardjubla** [comment]
Die Migration der AHV Nummern scheint zwischen 2.4.25 und 3.4.25 verloren gegangen zu sein:

Produktiv:
![Image](https://github.com/user-attachments/assets/2ef4262a-3156-4efa-b54b-5997fd44c777)


Testsystem:
![Image](https://github.com/user-attachments/assets/eb90b325-f4c5-4948-9113-563ca31b5969)


Ich habe bewusst auf dem Test- wie auch auf dem Produktivsystem die AHV-Nr. 756.1234.5678.97 vor dem Release in meinem Profil eingetragen. Nach dem Release fand ich diese in den Events an denen ich angemeldet bin. Jetzt sind die Daten im produktiven System verschwunden. Ich empfehle hier schnell eine analyse der Situation vorzunehmen. Wären die Daten weg, würde das für die vielen Event-Organisatoren welche die AHV-Nr. benötigen eine hiobsbotschaft.

**Comment by ThomasEllenberger** [comment]
@richardjubla 
Danke für die Meldung, wir sind dabei uns dies anzuschauen.
Aktuell sind wir uns noch nicht sicher, ob dies nur die Kurse betrifft bei denen die AHV-Frage ausgeblendet ist, oder sämtliche.
Wir analysieren dies noch weiter und melden uns bei dir, sobald wir mehr wissen.

**Comment by ThomasEllenberger** [comment]
Erkenntnisse:
Wir konnten diverse migrierte AHV-Nummern finden. Die Migration als grosses und ganzes hat also funktioniert.

AHV-Nummer wurde migriert wenn:
- Eine Person hat eine AHV-Nummer auf dem Profil hinterlegt.
- Das Event hat Start oder Enddatum in der Zukunft.
- Die AHV-Frage auf dem Event ist "Optional" oder "Obligatorisch"
- Bei der Eventanmeldung durch eine Person selbst wurde das Optionale AHV-Feld nicht gezielt leer gelassen.

AHV-Nummer wurde nicht migriert wenn:
- Events mit Start und Enddatum in der Vergangenheit.
- Die AHV-Frage auf dem Event ist "Nicht angezeigt"
- Eine Person hat sich selbst zu einem Event angemeldet auf dem die AHV-Frage bereits vorhanden war, und das ausfüllen "Optional" war und hat diese bewusst leer gelassen.
- 
Die AHV-Nummer wurde also nur in wenigen, ganz bestimmten Fällen nicht kopiert.
Wir gehen Stand heute davon aus, dass dies Fälle sind in welchen die AHV-Nummer nicht zwingend gebraucht wird.
Es würde nur Events betreffen in welchen die AHV-Nummer ohnehin von Personen welche sich selbst anmelden gar nicht verlangt wird (Frage wird "Nicht angezeigt") oder in welchen die Frage optional ist, und die Benutzer sich selbst bei ihrer Anmeldung aktiv dagegen entschieden haben diese auszufüllen.

Puzzle plant deshalb hier aktuell keine nach-Korrektur dieser Datenmigration.

**Comment by richardjubla** [comment]
Nachforschungen und prüfen dieser Regeln ist schwierig. 

Szenario: Wir haben einen Event (Jublasurium Lager) wo alle Anmeldungen mit einer AHV Nr. angemeldet waren. (Export liegt vor) 

- Eine Person hat eine AHV-Nummer auf dem Profil hinterlegt (nachvollziehbar im Log, Export liegt vor)
- Das Event hat Start oder Enddatum in der Zukunft. 
- Die AHV-Frage auf dem Event ist "Nicht angezeigt" (beim Laden der Event-Einstellungen durch bearbeiten des Events **ohne** abspeichern, verändert sich die Reihenfolge und evtl. auch der Status der Anmeldeangeben!)
-  Die AHV-Frage wurde im Rahmen von #58 im Event angepasst: Der Event wurde ursprünglich mit der jetzt fehlenden AHV Nr. über die Kontaktangaben aufgesetzt.

Anmeldungen ab dem 23.10.2024 sind ohne AHV Nr. Obwohl die AHV-Frage auf dem Event "Optional" ist, sind AHV Nr bis zum 23.10.2024 vorhanden. Vermutung: Mutation von AHV von Kontaktangaben zu Anmeldeangeben hat dazu geführt, dass dieses Feld nicht mehr korrekt abgefragt und mutiert wurde.
Bei allen Lager (Events) ist davon auszugehen, dass die AHV-Nummer gebraucht wird. 

cc @PhilippPBS

**Comment by ThomasEllenberger** [comment]
@richardjubla leider kann ich deinen Ausführungen oben nicht genau folgen.

Wenn ich es richtig verstehe, wurde auf dem erwähnten Event die AHV-Frage als "nicht angezeigt" definiert.
Entsprechend gibt es hier keine Frage, und auch keine Antworttabelle in welche wir die AHV-Nummer eintragen könnten.
Entsprechend wurde die AHV-Nummer vom Profil einer Person nicht in diesen Event überführt.

**Comment by richardjubla** [comment]
> [@richardjubla](https://github.com/richardjubla) leider kann ich deinen Ausführungen oben nicht genau folgen.
> 
> Wenn ich es richtig verstehe, wurde auf dem erwähnten Event die AHV-Frage als "nicht angezeigt" definiert. Entsprechend gibt es hier keine Frage, und auch keine Antworttabelle in welche wir die AHV-Nummer eintragen könnten. Entsprechend wurde die AHV-Nummer vom Profil einer Person nicht in diesen Event überführt.


Der erwähnten Event wurde vor der Umstellung von #58 aufgesetzt. Gehen wir davon aus, dass der Event dazwischen gar nie bearbeitet oder "definiert" wurde. 
Die AHV-Frage wurde (technisch) zum Event hinzugefügt. Die AHV-Nummer vom Profil wurden bei der Migration vom Profil einer Person in diesen Event überführt, aber halt "nur" bis 23.10.2024. In unserem Beispiel waren alle Anmeldungen mit AHV Nr. vorhanden. Jetzt nach der Mutation fehlen sie.
